Separate item_fn implementations
tcdi/pgx pull request #685
Opened 2022-09-13 19:42 UTC by willmurnane

There are two use cases which call `item_fn`:
* One when handling `#[pg_guard]`
* One when handling `#[pg_extern]`, which (almost always) eventually emits `#[pg_guard]` and leads to the first case
This lead to an unnecessary amount of confusion between the two cases. This PR splits the two cases into two functions, and does some small cleanup around the edges afterwards.

2022-09-17 05:08 UTC, workingjubilee requested changes
This will conflict with #615, which may still yet receive final-pass revisions. It cannot land before then, and after it does, I will be pushing towards `0.5.0`.

2022-09-21 11:11 UTC, willmurnane commented
This now winds up just eliminating a big swath of unused code :)

2022-09-21 16:00 UTC, willmurnane commented on pgx-utils/src/rewriter.rs
> +                pg_sys::guard::guard( || #func_name(#arg_list) )
This is effectively the code from line 491, but we're always doing the `no_guard = false` case so I inlined it.

2022-09-21 20:27 UTC, workingjubilee commented
what, seriously? half this code is just unused...?

2022-09-21 20:30 UTC, willmurnane commented
Nope, 3/4s. There used to be two ways that `item_fn` was called, and it in turn called `item_fn_with_rewrite` or `item_fn_without_rewrite` as appropriate. One of those was eliminated in #615, and the other greatly simplified, so that only `item_fn_without_rewrite` remained. So we can eliminate all of the `item_fn_with_rewrite` code and all of its dependencies.

2022-09-21 20:47 UTC, workingjubilee approved these changes
amazing.

2022-09-21 20:51 UTC, merged