Implement SPI_connect_ext and related functionality
tcdi/pgx pull request #714
Opened 2022-09-27 20:41 UTC by yrashk

This allows pgx users to use SPI in a non-atomic fashion.

2022-09-27 23:26 UTC, workingjubilee commented
I'm expecting the tests will break on pg10.

2022-09-27 23:37 UTC, workingjubilee requested changes
I don't really want all of these to be safely wrapped like this at the moment, see this conversation:
- https://github.com/tcdi/pgx/issues/696

However, if the implementation was sufficiently high quality (i.e. enforced tx/rollback correctness by lifting that constraint into the type level), I would consider it.

I would also accept an implementation of the resolution I was inclined to try (namely, saying "we may or may not use `SPI_connect_ext` at our option" and setting flags implicitly on an experimental basis, so as to see how that pans out for users).

2022-09-27 23:37 UTC, workingjubilee commented on pgx/src/spi.rs
> +        unsafe { pg_sys::SPI_rollback_and_chain() }
These need `// SAFETY` explanations.

2022-09-27 23:37 UTC, workingjubilee commented on pgx/src/spi.rs
> +    /// Otherwise, calling those functions will result in an immediate error.
There's no reason to rely on global mutable state for this if we are going to expose a safe wrapper: these kinds of predicates should be enforced at the type level.

2022-09-27 23:37 UTC, workingjubilee commented on pgx/src/spi.rs
> +                Spi::check_status(unsafe { pg_sys::SPI_connect_ext(flags as _) });
I do not believe this function exists in Postgres 10, this requires `#[cfg]`.

2022-09-27 23:37 UTC, workingjubilee commented on pgx/src/spi.rs
> +            pg_sys::SPI_OPT_NONATOMIC
I do not believe this exists in Postgres 10. This requires `#[cfg]`.

2022-10-01 20:11 UTC, yrashk commented
Thank you for the feedback; I will address your commentary in the coming days. This is a lower-priority development for me at the moment, but I'll see what I can do.

2022-10-07 01:46 UTC, workingjubilee commented
Another solution to the issues regarding Postgres 10 may just be waiting for a bit: we're going to be dropping Postgres 10 sometime soon.

2022-10-21 21:44 UTC, yrashk commented
I'll retire this for now, as it has become stale. May reopen later. WIth sub-transactions available through pgx-contrib-spiext, a bit less of a pressing concern.

2022-10-21 21:44 UTC, closed without merging