Set timezone to UTC in tests
tcdi/pgx pull request #826
Opened 2022-10-28 20:41 UTC by Smittyvb

Sets the timezone to UTC by default. This removes the need to do a `SET TIME ZONE 'UTC'` in every test that does stuff with dates, which can occur a lot in some extensions.

I also updated the CI to use the [Pacific/Chatham (UTC+12:45)](https://en.wikipedia.org/wiki/Chatham_Standard_Time_Zone) so that the timezone-invariance of the tests is verified in CI.

2022-10-28 21:58 UTC, workingjubilee requested changes
Would you be so kind as to document the reason for such a deliberately eccentric timezone in the file? It doesn't seem like it will remain obvious in the future.

2022-10-28 21:58 UTC, workingjubilee commented on pgx-tests/src/tests/datetime_tests.rs
>          // prevents PG's timestamp serialization from imposing the local servers time zone
```suggestion
```

2022-11-02 19:26 UTC, workingjubilee commented
We talked about this and think that we want to make sure it is easily configurable by the users through PGX for setting the timezone for tests rather than setting it like this for everyone. It's not really clear how to override this.

2022-11-02 19:30 UTC, Smittyvb commented
@workingjubilee You can override this by doing this in the `pg_test` module:
```rust
#[cfg(test)]
pub mod pg_test {
    ...
    pub fn postgresql_conf_options() -> Vec<&'static str> {
        // return any postgresql.conf settings that are required for your tests
        vec![
            "America/Blah"
        ]
    }
}
```

since later config entries overrides earlier ones.

Actually, another way of implementing this PR would be to make the default project files specify a timezone in the `postgresql_conf_options`, and letting the user remove that line if they wish. Would you prefer that way?

2022-11-02 20:05 UTC, eeeebbbbrrrr commented
> since later config entries overrides earlier ones.

This sounds like relying on a Postgres implementation detail that's subject to change.

I'm not overly excited about defaulting tests to run in UTC when it's easy enough for extension authors to set it.

> Another way of implementing this PR would be to make the default project files specify a timezone in the postgresql_conf_options, and letting the user remove that line if they wish. Would you prefer that way?

Maybe something like changing the function definition to:

```rust
fn postgres_conf_options(timezone: &mut Option<String>) -> Vec<String> {

}
```

Where pgx calls it with either `Some("UTC")` or even `None`.  If the user wants to change it, they can `*timezone = Some("America/Blah");`

2022-11-02 20:34 UTC, workingjubilee commented
I'm okay with generating the `postgresql_conf_options` with a default timezone in them. An explicit timezone arg seems dandy too. It definitely is something we should be aiming at making clear and user-visible it is happening, whatever way we do it.

As someone who's better at Rust than SQL or Postgres implementation details (though the last one is catching up frighteningly fast...), I shouldn't have to know about the intricacies of how configuring the timezone goes down. Ideally I would rather not even know about the `SET TIME ZONE` SQL command! I should just be able to see a line of configuration code and change it however I need it to be.

2022-11-03 15:56 UTC, Smittyvb commented
I updated the PR to generate the `postgresql_conf_options` with a default UTC timezone.

2022-11-10 05:20 UTC, eeeebbbbrrrr commented
Hey. I’m just gonna close this. I’m not convinced this is something pgx should be doing. 

It’s really simple for an extension to set the time zone it needs during testing and pgx forcing it to be something other than the server default is really surprising. 

I do appreciate your efforts here, @Smittyvb.

2022-11-10 05:20 UTC, closed without merging