Problem: can't use `pg_guard` on parameterized functions
tcdi/pgx pull request #918
Opened 2022-12-05 19:14 UTC by yrashk

This code won't compile:

```rust
extern "C" fn extern_func_impl<T>() -> bool {
    true
}
```

The error is

```
error[E0282]: type annotations needed
```

Solution: ensure this case is handled

2022-12-05 19:21 UTC, eeeebbbbrrrr approved these changes
oh, good one!

I'll merge soon as CI passes.  Thanks @yrashk!

2022-12-05 21:18 UTC, yrashk commented
You can merge it now :)

2022-12-06 01:41 UTC, workingjubilee requested changes
Mmm. Using a type generic or const generic in a function, as opposed to a lifetime generic, is incompatible with `#[no_mangle]`. Rejecting type generics for `#[pg_guard]`, which is often used in concert with `#[no_mangle]`, is thus the correct behavior. PGX often does this, in particular. However, this change is still permissible if we have a separate enforcement strategy that specifically catches the case of a function annotated with both `#[no_mangle]` and `#[pg_guard]`. Otherwise I believe we are exposing ourselves to accidentally allowing significant miscompilations.

2022-12-06 01:57 UTC, yrashk commented
I'll take care of this case

2022-12-06 02:17 UTC, yrashk commented
@workingjubilee great catch; I've addressed your concern. Let me know if this looks good!

2022-12-06 02:27 UTC, workingjubilee approved these changes
Excellent, this is now fine!

2022-12-06 02:27 UTC, workingjubilee commented on pgx-tests/src/tests/pg_guard_tests.rs
> +// #[no_mangle]
We should have some kind of compiletest-like suite, so we can test for compile failures.

2022-12-06 16:17 UTC, eeeebbbbrrrr commented
I'll merge this into develop and then manually fix it for 0.6.1 -- `rewriter.rs` is in a different place now

2022-12-06 16:19 UTC, merged